version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: infrapulse-grafana
    ports:
      - "3000:3000"
    volumes:
      - ../grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
